[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "finnhub-python>=2.4.22",
    "trafilatura>=2.0.0",
    "twilio>=9.4.5",
]
